workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Dub.co API:
        inputs:
            - location: https://api.pimms.io
        registry:
            location: registry.speakeasyapi.dev/pimms/pimms-ts/dub-co-api
targets:
    pimms:
        target: typescript
        source: Dub.co API
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/pimms/pimms-ts/dub-co-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
